### ISSUE TITLE
Optimize `fix()`

### ISSUE THREAD

**Issue by alexypdu** [datastructures-js/heap#26]
Hello, I think we can optimize `fix()` to improve it from $O(nlogn)$ to $O(n)$. Instead of doing this:

```js
fix() {
  for (let i = 0; i < this.size(); i += 1) {
    this._heapifyUp(i);
  }
  return this;
}
```

we can do this:

```js
fix() {
  for (let i = this.size() - 1; i >= 0; --i) {
    this._heapifyDown(i);
  }:)
  return this;
}
```

As suggested [here](https://stackoverflow.com/a/18742428), we should go in the opposite direction: start at the end of the array and move back towards the front. At each iteration, we sift an item down until it is in the correct location. I can submit a pull request if you think it's good to go :)

**Comment by eyas-ranjous** [comment]
@alexypdu hi! Thanks for the suggestion. You can go ahead and submit a pr. My only request is to make sure that tests are good with that change, and if possible to provide a benchmark (nothing complicated) that shows some runtime difference between the two approaches. I guess using some big size input example. And I am happy to merge it.
