### ISSUE TITLE
If a heap is valid, is leaf() guaranteed to return the max/min value

### ISSUE THREAD

**Issue by k290** [datastructures-js/heap#34]
If I have a minHeap that is valid, will leaf() always return the maximum value?

Similarly if I have a maxHeap that is valid, will leaf() always return the minimum value?

**Comment by eyas-ranjous** [comment]
Yes. `.leaf()` will always return the right value for all heap types for valid heaps. Also `.fix()` will fix the leaf value as well as the positions.
